"""
Configuration package exports.
"""
from src.config.base import (
    DEFAULT_ENCODING,
    DEFAULT_SEPARATOR,
    DEFAULT_UBIGEO_PREFIXES,
    VALID_SURVEY_RESULTS,
    PRIMARY_KEY_HOUSEHOLD,
    PRIMARY_KEY_INDIVIDUAL,
)
from src.config.modulo01 import (
    COLUMNS_RENAME_MOD01,
    CATEGORICAL_MAPPINGS_MOD01,
    DWELLING_INHERITANCE_COLUMNS,
    STRICT_NON_NULL_COLUMNS_MOD01,
    MIN_EXPECTED_ROWS_LIMA_CALLAO,
    MAX_EXPECTED_ROWS_LIMA_CALLAO,
)

__all__ = [
    "DEFAULT_ENCODING",
    "DEFAULT_SEPARATOR",
    "DEFAULT_UBIGEO_PREFIXES",
    "VALID_SURVEY_RESULTS",
    "PRIMARY_KEY_HOUSEHOLD",
    "PRIMARY_KEY_INDIVIDUAL",
    "COLUMNS_RENAME_MOD01",
    "CATEGORICAL_MAPPINGS_MOD01",
    "DWELLING_INHERITANCE_COLUMNS",
    "STRICT_NON_NULL_COLUMNS_MOD01",
    "MIN_EXPECTED_ROWS_LIMA_CALLAO",
    "MAX_EXPECTED_ROWS_LIMA_CALLAO",
]
